version: "3"

services:
    # rever proxy server
    nginxproxy:
        image: nginx:1.18.0
        ports:
            - "80:80"
        restart: always
        volumes:
            - "./nginx/nginx.conf:/etc/nginx/nginx.conf"

    # backend WAS
    nest:
        depends_on:
          - nginxproxy
          - db
        build:
          context: ./backend
          dockerfile: Dockerfile
        restart: always

    # frontend server (Next.js)
    next:
        depends_on:
          - nginxproxy
        build:
          context: ./frontend
          dockerfile: Dockerfile
        # volumes:
        #   - "./frontend:/app/frontend/next"
        restart: always

    db:
      image: postgres:14-alpine
      ports:
        - "5433:5432"
      restart: always
      environment:
        POSTGRES_USERNAME : "postgres"            
        POSTGRES_PASSWORD : "1234"
      volumes:
        - "./db/var/run/postgresql:/var/run/postgresql"
        
